# Étape 1 : Choisir l'image de base
FROM python:3.9-slim

# Étape 2 : Définir le dossier de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers locaux vers le conteneur
COPY . .

# Étape 4 : Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Étape 5 : Commande à lancer quand le conteneur démarre
CMD ["python", "app.py"]